apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  jobTemplate:
    metadata:
      name: backup
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: alpine
            name: backup
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 0 8-14 * 2
status: {}
