apiVersion: v1
kind: Pod
metadata:
  name: broken-pod-2
spec:
  nodeSelector:
    disktype: ssd-fast-pcie-gen4
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
