apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) >> /data/log.txt; sleep 5; done"]
    volumeMounts:
    - name: node-storage
      mountPath: /data
  volumes:
  - name: node-storage
    hostPath:
      path: /tmp/k8s-hostpath
      type: DirectoryOrCreate

