apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-shell
  name: temp-shell
spec:
  containers:
  - image: ubuntu
    name: temp-shell
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
