apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-cluster
  name: web-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-cluster
  strategy: {}
  template:
    metadata:
      labels:
        app: web-cluster
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
