apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        resources: {}
status: {}
