apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-env-1
  name: drill-env-1
spec:
  containers:
  - env:
    - name: DB_HOST
      value: postgres.example.com
    - name: LOG_LEVEL
      value: debug
    image: nginx
    name: drill-env-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
