apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-ports-2
  name: drill-ports-2
spec:
  containers:
  - image: nginx
    name: drill-ports-1
    ports:
    - containerPort: 80
      name: "http"
      protocol: "TCP"
    - containerPort: 443
      name: "https"
      protocol: "TCP"
    - containerPort: 9090
      name: "metrics"
      protocol: "TCP"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
