apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-resources
  name: drill-resources
spec:
  containers:
  - image: nginx
    name: drill-resources
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
