apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-security
  name: drill-security
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
  - image: nginx
    name: drill-security
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
