apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug-box
  name: debug-box
spec:
  containers:
  - image: busybox
    name: debug-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
