apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-pod-1
  name: drill-pod-1
spec:
  containers:
  - image: nginx
    name: drill-pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
