apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drill-pod-2
  name: drill-pod-2
spec:
  containers:
  - image: nginx
    name: drill-pod-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
