apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: final-deploy
  name: final-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: final-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
