apiVersion: batch/v1
kind: Job
metadata:
  name: gp-job
spec:
  template:
    metadata: {}
    spec:
      containers:
      - image: busybox
        name: gp-job
        resources: {}
      restartPolicy: Never
status: {}
