apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gp-pod
  name: gp-pod
spec:
  containers:
  - image: nginx
    name: gp-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
