apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gp-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gp-role
subjects:
- kind: ServiceAccount
  name: gp-sa
  namespace: default
