apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-cache
  name: test-cache
spec:
  containers:
  - image: redis
    name: test-cache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
