apiVersion: v1
kind: Pod
metadata:
  labels:
    run: warmup-pod
  name: warmup-pod
spec:
  containers:
  - image: nginx
    name: warmup-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
